Repository sqreen/go-agent, pull requests merged in 2020-07, with the labels that each got.

#130 Protect the request body with the In-App WAF
  internal/adapter.go
  internal/backend/api/api.go
  internal/backend/api/json.go
  internal/backend/client_test.go
  internal/binding-accessor/exec.go
  internal/protection/http/bindingaccessor.go
  internal/protection/http/bindingaccessors_test.go
  internal/protection/http/http.go
  internal/protection/http/http_test.go
  internal/protection/http/types/types.go
  internal/protection/http/types/types_test.go
  internal/rule/callback.go
  internal/rule/callback/bindingaccessors.go
  internal/rule/callback/factory.go
  internal/rule/callback/ip-denylist_test.go
  internal/rule/callback/javascript.go
  internal/rule/callback/javascript_test.go
  internal/rule/callback/types.go
  internal/rule/callback/waf.go
  internal/rule/factory.go
  internal/rule/rule.go
  internal/sqlib/sqhook/hook.go
  internal/sqlib/sqsafe/call.go
  internal/sqlib/sqsafe/call_test.go
  sdk/middleware/sqecho/echo.go
  sdk/middleware/sqgin/gin.go
  sdk/middleware/sqhttp/http.go
  sdk/middleware/sqhttp/http_test.go
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: enhancement

#129 Update the blocking page
  internal/rule/callback/write-custom-error-page.go
Labels: enhancement

#131 v0.12.0
  .dockerignore
  CHANGELOG.md
  internal/adapter.go
  internal/backend/api/api.go
  internal/backend/api/json.go
  internal/backend/api/signal/signal.go
  internal/backend/client_test.go
  internal/binding-accessor/exec.go
  internal/event/record.go
  internal/protection/http/bindingaccessor.go
  internal/protection/http/bindingaccessors_test.go
  internal/protection/http/http.go
  internal/protection/http/http_test.go
  internal/protection/http/types/types.go
  internal/protection/http/types/types_test.go
  internal/rule/callback.go
  internal/rule/callback/bindingaccessors.go
  internal/rule/callback/factory.go
  internal/rule/callback/ip-denylist_test.go
  internal/rule/callback/javascript.go
  internal/rule/callback/javascript_test.go
  internal/rule/callback/types.go
  internal/rule/callback/waf.go
  internal/rule/callback/write-custom-error-page.go
  internal/rule/factory.go
  internal/rule/rule.go
  internal/sqlib/sqhook/hook.go
  internal/sqlib/sqsafe/call.go
  internal/sqlib/sqsafe/call_test.go
  internal/version/version.go
  sdk/middleware/sqecho/echo.go
  sdk/middleware/sqgin/gin.go
  sdk/middleware/sqhttp/http.go
  sdk/middleware/sqhttp/http_test.go
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: release

#133 v0.12.1
  CHANGELOG.md
  go.mod
  go.sum
  internal/backend/api/api.go
  internal/backend/api/json_test.go
  internal/binding-accessor/binding-accessor_test.go
  internal/binding-accessor/exec.go
  internal/protection/http/bindingaccessor.go
  internal/protection/http/http.go
  internal/rule/callback/waf.go
  internal/version/version.go
Labels: release

#135 protection/http: finer-grained instrumentation
  internal/protection/http/http.go
  internal/protection/http/request.go
Labels: enhancement, internals

#136 sqlib/sqhook: allow attaching multiple rules per hook point
  internal/backend/api/api.go
  internal/rule/callback/add-security-headers.go
  internal/rule/instrumentation.go
  internal/rule/rule.go
  internal/rule/rule_test.go
  internal/rule/rule_unit_test.go
  internal/sqlib/sqassert/assert.go
  internal/sqlib/sqassert/assert_disabled.go
  internal/sqlib/sqerrors/errors.go
  internal/sqlib/sqerrors/errors_test.go
  internal/sqlib/sqhook/hook.go
  internal/sqlib/sqhook/hook_test.go
  internal/sqlib/sqhook/hook_unit_test.go
  internal/sqlib/sqhook/validation_test.go
Labels: enhancement, internals

#137 sdk/sqreen-instrumentation-tool: add limited instrumentation of go.mongodb.org/mongo-driver/mongo
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: enhancement

#138 agent/backend: add sqreen domains health checking
  go.mod
  go.sum
  internal/adapter.go
  internal/agent.go
  internal/backend/api/api.go
  internal/backend/api/json_test.go
  internal/backend/client.go
  internal/backend/client_test.go
  internal/client.go
  internal/config/config.go
  internal/config/config_test.go
  internal/sqlib/sqsanitize/sanitize.go
  internal/sqlib/sqsanitize/sanitize_test.go
Labels: internals

#139 Fix a possible empty batch being sent
  internal/agent.go
  internal/backend/api/signal/signal.go
  internal/backend/client.go
Labels: bug

#140 scubbing: fix the waf metadata scrubbing
  internal/backend/api/api.go
  internal/backend/api/json_test.go
  internal/sqlib/sqsanitize/sanitize.go
  internal/sqlib/sqsanitize/sanitize_test.go
Labels: bug, internals

#141 v0.13.0
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  internal/adapter.go
  internal/agent.go
  internal/backend/api/api.go
  internal/backend/api/json_test.go
  internal/backend/api/signal/signal.go
  internal/backend/client.go
  internal/backend/client_test.go
  internal/client.go
  internal/config/config.go
  internal/config/config_test.go
  internal/protection/http/http.go
  internal/protection/http/request.go
  internal/rule/callback/add-security-headers.go
  internal/rule/instrumentation.go
  internal/rule/rule.go
  internal/rule/rule_test.go
  internal/rule/rule_unit_test.go
  internal/sqlib/sqassert/assert.go
  internal/sqlib/sqassert/assert_disabled.go
  internal/sqlib/sqerrors/errors.go
  internal/sqlib/sqerrors/errors_test.go
  internal/sqlib/sqhook/hook.go
  internal/sqlib/sqhook/hook_test.go
  internal/sqlib/sqhook/hook_unit_test.go
  internal/sqlib/sqhook/validation_test.go
  internal/sqlib/sqsanitize/sanitize.go
  internal/sqlib/sqsanitize/sanitize_test.go
  internal/version/version.go
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: release

#142 RASP: add shellshock protection
  internal/backend/api/signal/signal.go
  internal/rule/callback/shellshock.go
  internal/rule/callback/shellshock_unit_test.go
  internal/rule/factory.go
Labels: enhancement

#143 System tests CI
  .github/workflows/system-tests.yaml
Labels: enhancement, internals
