Repository sqreen/go-agent, pull requests merged in 2020-09, with the labels that each got.

#145 agent/rule/callback/waf: always recover panics
  go.mod
  go.sum
  internal/rule/callback/waf.go
Labels: enhancement, internals

#146 Github Actions CI
  .github/workflows/agent-tests.yaml
  .github/workflows/example-apps.yaml
  .github/workflows/system-tests.yaml
  azure-pipelines.yml
  tools/azure-pipelines/docker-golang.yml
  tools/docker/dev/Dockerfile
Labels: enhancement, internals

#147 v0.14.0
  .github/workflows/agent-tests.yaml
  .github/workflows/example-apps.yaml
  .github/workflows/system-tests.yaml
  CHANGELOG.md
  azure-pipelines.yml
  go.mod
  go.sum
  internal/backend/api/signal/signal.go
  internal/rule/callback/shellshock.go
  internal/rule/callback/shellshock_unit_test.go
  internal/rule/callback/waf.go
  internal/rule/factory.go
  internal/version/version.go
  tools/azure-pipelines/docker-golang.yml
  tools/docker/dev/Dockerfile
Labels: release

#148 agent/protection/http: lazy access to post form values
  internal/adapter.go
  internal/protection/http/bindingaccessor.go
  internal/protection/http/bindingaccessors_test.go
  internal/protection/http/http_test.go
  internal/protection/http/request.go
  internal/protection/http/types/types.go
  internal/rule/callback/ip-denylist_test.go
  sdk/middleware/sqecho/echo.go
  sdk/middleware/sqgin/gin.go
  sdk/middleware/sqhttp/http.go
  sdk/middleware/sqhttp/http_test.go
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: bug

#149 Call Count Monitoring of RASP and In-App WAF callbacks
  internal/agent.go
  internal/backend/api/api.go
  internal/rule/callback.go
  internal/rule/callback/callback_test.go
  internal/rule/callback/javascript.go
  internal/rule/callback/shellshock.go
  internal/rule/callback/types.go
  internal/rule/callback/waf.go
  internal/rule/rule.go
Labels: enhancement, internals

#150 v0.15.0
  CHANGELOG.md
  internal/adapter.go
  internal/agent.go
  internal/backend/api/api.go
  internal/protection/http/bindingaccessor.go
  internal/protection/http/bindingaccessors_test.go
  internal/protection/http/http_test.go
  internal/protection/http/request.go
  internal/protection/http/types/types.go
  internal/rule/callback.go
  internal/rule/callback/callback_test.go
  internal/rule/callback/ip-denylist_test.go
  internal/rule/callback/javascript.go
  internal/rule/callback/shellshock.go
  internal/rule/callback/types.go
  internal/rule/callback/waf.go
  internal/rule/rule.go
  internal/version/version.go
  sdk/middleware/sqecho/echo.go
  sdk/middleware/sqgin/gin.go
  sdk/middleware/sqhttp/http.go
  sdk/middleware/sqhttp/http_test.go
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: release

#152 Enable partial instrumentation of Echo
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: enhancement

#153 agent/rule/shellshock: fix splitting environment variables
  internal/rule/callback/shellshock.go
Labels: bug

#155 Middleware for Echo v4
  go.mod
  go.sum
  sdk/middleware/sqecho/v4/echo.go
  sdk/middleware/sqecho/v4/echo_test.go
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: enhancement

#154 v0.16.0
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  internal/rule/callback/shellshock.go
  internal/version/version.go
  sdk/middleware/sqecho/v4/echo.go
  sdk/middleware/sqecho/v4/echo_test.go
  sdk/sqreen-instrumentation-tool/instrumentation.go
Labels: release

#158 PII: fix In-App WAF attack sanitization
  internal/backend/api/api.go
  internal/backend/api/api_test.go
  internal/sqlib/sqsanitize/sanitize.go
  internal/sqlib/sqsanitize/sanitize_test.go
Labels: bug

#159 sdk/middleware: fix http response content status and length monitoring
  sdk/middleware/sqecho/echo.go
  sdk/middleware/sqecho/echo_test.go
  sdk/middleware/sqgin/gin.go
  sdk/middleware/sqgin/gin_test.go
  sdk/middleware/sqhttp/http_test.go
Labels: bug

#157 sdk/middleware/sqgin: fix request ctx
  sdk/middleware/sqecho/echo_test.go
  sdk/middleware/sqgin/gin.go
  sdk/middleware/sqgin/gin_test.go
  sdk/middleware/sqhttp/http_test.go
Labels: bug

#160 v0.16.1
  CHANGELOG.md
  README.md
  internal/backend/api/api.go
  internal/backend/api/api_test.go
  internal/sqlib/sqsanitize/sanitize.go
  internal/sqlib/sqsanitize/sanitize_test.go
  internal/version/version.go
  sdk/middleware/sqecho/echo.go
  sdk/middleware/sqecho/echo_test.go
  sdk/middleware/sqecho/v4/README.md
  sdk/middleware/sqgin/README.md
  sdk/middleware/sqgin/gin.go
  sdk/middleware/sqgin/gin_test.go
  sdk/middleware/sqhttp/http_test.go
Labels: release
